### PR TITLE
A couple of features for Options

### PR DESCRIPTION
**Pull request by asajeffrey**
A couple of changes to option-handling:
- allow demo apps to provide default options
- add an option to disable the UI

### CODE REVIEW

**Comment by asajeffrey** [comment]
Rebased.

**Comment by asajeffrey** [comment]
Review ping?

**Comment by pcwalton** [comment]
I think turning off the UI would be good in general. Maybe allow the Tab key to cycle through "full UI", "only debug window", "no UI" options, and then add a command line switch to start in one of those modes.

**Comment by asajeffrey** [comment]
Done.

**Pull request merged**
