### PR TITLE
Magicleap demo

### PR DESCRIPTION
**Pull request by asajeffrey**
This PR adds a magicleap demo to PF3.

### CODE REVIEW

**Comment by asajeffrey** [comment]
This demo disables jemalloc, I should find out how to re-enable it.

**Comment by asajeffrey** [comment]
Rebased, and added the demo launcher.

**Comment by jdm** [comment]
Rebased and merged in #133.

**Comment by asajeffrey** [comment]
Yay!

**Comment by asajeffrey** [comment]
Merged as part of #133.

**Pull request closed without merging**
