### PR TITLE
chore: use freetype to replace freetype-sys

### PR DESCRIPTION
**Pull request by Brooooooklyn**
I'm trying to build a node canvas with rust: [context_2d](https://github.com/rust-canvas/rust-canvas/blob/feature/font-renderer/src/canvas/context_2d.rs#L121), and borrowed tones of codes from [servo](https://github.com/servo/servo/blob/master/components/canvas/canvas_paint_thread.rs).

When I was trying to built it on linux, it crashed with:

```
error: multiple packages link to native library `freetype`, but a native library can be linked only once

package `servo-freetype-sys v4.0.3`
    ... which is depended on by `azure v0.25.0`
    ... which is depended on by `rustcanvas v0.1.0 (file:///Users/longyinan/workspace/Github/rust-canvas)`
links to native library `freetype`

package `freetype-sys v0.6.0`
    ... which is depended on by `pathfinder_font_renderer v0.1.0 (https://github.com/rust-canvas/pathfinder?branch=rust-canvas#5f082aa4)`
    ... which is depended on by `rustcanvas v0.1.0 (file:///Users/longyinan/workspace/Github/rust-canvas)`
also links to native library `freetype`
```

So I change the dependencies in pathfinder to pass the compile, and I have no idea about the differences between the `freetype-sys` & `freetype`.

Please tell me if you think this Pull Request is unreasonable, and feel free to close it.

### CODE REVIEW

**Comment by messense** [comment]
It fails to compile because `freetype-sys` specified [`links`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#the-links-manifest-key) key in its [`Cargo.toml`](https://github.com/PistonDevelopers/freetype-sys/blob/d62a4a01d02c959cd61db75d715d4bca802fc1d5/Cargo.toml#L6) which is sensible IMO.

**Comment by Brooooooklyn** [comment]
Yes, I know what caused built failed, what I don't understand is, what's the `differences between the freetype-sys & freetype`.

**Comment by messense** [comment]
I think the differences is that `freetype-sys` only **dynamically links** to `libfreetype2` installed on your system, while `freetype` by default depends on [`servo-freetype-sys`](https://github.com/servo/libfreetype2) which bundles `libfreetype2` source code and **links to it statically**.

**Comment by pcwalton** [comment]
I'm a bit confused as to what's going on with this PR.

**Comment by Brooooooklyn** [comment]
ehh.. it's just make `pathfinder` work with [rust-azure](https://github.com/servo/rust-azure)

**Comment by pcwalton** [comment]
I'm going to go ahead and close this in favor of the current dynamic linking behavior, but feel free to reopen if a better solution is found.

**Pull request closed without merging**
