### PR TITLE
Update lyon and euclid dependencies

### PR DESCRIPTION
**Pull request by nical**
Needed for https://github.com/servo/webrender/pull/2882

### CODE REVIEW

**Comment by nical** [comment]
cc @BorisChiou

**Comment by nical** [comment]
Note that lyon crates reexpose their public dependencies so I changed most of the code that depend on both lyon_geom and lyon_path to only depend only on lyon_path. That way there's a little less work to do to update the two (new versions of the lyon crates are always published at the same time). lyon_geom also reexports euclid but I didn't touch that in most places as pathfinder uses certain euclid feature flags.

**Comment by BorisChiou** [comment]
Awesome! Thanks for this patch.

**Comment by nox** [comment]
@pcwalton Can we move this repository to the Servo organisation? Thanks.

**Pull request merged**
