### PR TITLE
In a VR demo, run the eyes in parallel

### PR DESCRIPTION
**Pull request by asajeffrey**
Running the two eyes concurrently takes the CPU time down from ~1.8ms to ~1.4ms on my iMac.

### CODE REVIEW

**Comment by asajeffrey** [comment]
Rebased. Review ping @pcwalton?

**Comment by asajeffrey** [comment]
It looks like pipelining makes this optimization difficult, since all the messages for camera 0 have to arrive before any of the messages for camera 1, so we'd need buffering to run the two cameras concurrently.

**Comment by pcwalton** [comment]
Also, pipelining already achieves some of the gains from this, because it runs the sequential bottleneck in parallel with the tiling.

**Comment by pcwalton** [comment]
This is no longer relevant with reprojection.

**Pull request closed without merging**
