### PR TITLE
Add Transform3DF32::from_quaternion

### PR DESCRIPTION
**Pull request by asajeffrey**
Add a function to build a transform from a quaternion.

### CODE REVIEW

**Comment by pcwalton** [comment]
Needs SIMD

**Comment by asajeffrey** [comment]
Why does this need SIMD but, e.g, `from_ortho` doesn't? If it makes any difference, the way this is going to be used it won't be on a hot path. We could check it in with a `TODO: SIMD?`

**Comment by pcwalton** [comment]
The code will be clearer with SIMD. Give me a few minutes and I'll make a go of it.

**Comment by pcwalton** [comment]
(I'd also prefer to use rotors instead of quaternions, but I'm OK with deferring that.)

**Comment by pcwalton** [comment]
I pushed this patch, partially SIMD-ified: https://github.com/pcwalton/pathfinder/commit/26fea26f87427b1ac179f0ed77c6fc9bbc155b13

(It's untested but I triple checked it.)

Thanks for the patch!

**Pull request closed without merging**
